Restplus order
NYU-DevOps2020-shopcarts/shopcarts pull request #132
Opened 2020-11-23 02:10 UTC by KHafner

This PR refactors the current service to use Flask-RESTPlus for Shopcart Place-Order Action.

## Checklist:

- [X] I have written test cases for this change, and my code passed the test
- [X] I have attached this PR to an issue/user story

2020-11-23 04:47 UTC, iLtc requested changes

2020-11-23 04:47 UTC, iLtc commented on service/routes.py
> +    @api.response(404, 'Shopcart not found or is empty')
Please add a new response for 204

2020-11-23 16:05 UTC, iLtc approved these changes
LGTM, thanks!

2020-11-23 18:39 UTC, gauridhawan approved these changes
LGTM!

2020-11-23 20:31 UTC, merged

2020-11-23 20:38 UTC, KHafner commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201123-203830 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201123-203830") to [dev](https://console.bluemix.net/apps/4aa42608-55fd-40d6-b27b-d99aa18a0658?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit 9435baadecc392cb889db30217cc58dd69fa2e7b

2020-12-08 14:40 UTC, KHafner commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit 9435baadecc392cb889db30217cc58dd69fa2e7b