Item resource
NYU-DevOps2020-shopcarts/shopcarts pull request #136
Opened 2020-11-24 15:14 UTC by nonococoleo

# Pull Request Template

In this PR, shopcart item has been Refactored to resources, related api path has changed

## Checklist:

- [x] I have written test cases for this change, and my code passed the test
- [x] I have updated documentation to reflect this change
- [x] I have attached this PR to an issue/user story

2020-11-25 05:07 UTC, iLtc requested changes

2020-11-25 05:07 UTC, iLtc commented on service/routes.py
> +    @api.response(404, 'Shopcart Item not found')
Please add a 200 response here

2020-11-25 05:07 UTC, iLtc commented on service/routes.py
> +    @api.response(400, 'The posted Item data was not valid')
Please add a 200 response here

2020-11-25 05:07 UTC, iLtc commented on service/routes.py
> +        data = request.get_json()
Please use `api.payload` instead of `request.get_json()`

2020-11-25 15:30 UTC, KHafner approved these changes

2020-11-25 16:18 UTC, iLtc approved these changes
LGTM, thanks!

2020-11-26 01:24 UTC, merged

2020-11-26 01:31 UTC, KHafner commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201126-013055 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201126-013055") to [dev](https://console.bluemix.net/apps/4aa42608-55fd-40d6-b27b-d99aa18a0658?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit e391d7b2aea41a9554805348c53b2234d191cc5b

2020-12-08 14:40 UTC, KHafner commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit e391d7b2aea41a9554805348c53b2234d191cc5b