ShopcartItemCollection updates to routes and tests
NYU-DevOps2020-shopcarts/shopcarts pull request #137
Opened 2020-11-25 21:58 UTC by jules203

# Pull Request Template

## Checklist:

- [x] I have written test cases for this change, and my code passed the test - updated test cases with new api route
- [x] I have attached this PR to an issue/user story

may need some help de-bugging code!

2020-11-26 02:30 UTC, iLtc requested changes

2020-11-26 02:30 UTC, iLtc commented on service/routes.py
> +@api.route('/shopcarts/items', strict_slashes=False)
The route should be `/shopcarts/:id/items`

2020-11-26 02:30 UTC, iLtc commented on service/routes.py
We should also add a POST method here to replace `create_shopcart_items`

2020-11-26 02:30 UTC, iLtc commented on service/routes.py
> +    @api.marshal_list_with(shopcart_item_model)
Please include `@api.response(200, 'Shopcart Items List')`

2020-11-27 18:53 UTC, jules203 commented
Thank you @iLtc !!

2020-11-27 23:29 UTC, KHafner approved these changes

2020-11-28 02:35 UTC, nonococoleo approved these changes

2020-11-28 18:31 UTC, iLtc approved these changes

2020-11-28 18:31 UTC, merged

2020-11-28 18:39 UTC, KHafner commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201128-183905 "deploy-ibm-yp-us-south-kfh226-nyu.edu-dev-20201128-183905") to [dev](https://console.bluemix.net/apps/4aa42608-55fd-40d6-b27b-d99aa18a0658?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:dev"), including commit a1564bf02f0c1f066ceea9d42a70dcf118400443

2020-12-08 14:40 UTC, KHafner commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b5c2987e-b3d1-4601-9f28-34419832137d?env_id=ibm:yp:us-south "nyu-shopcart-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/c869c127-ceda-423d-80b8-f74ee52b7378 "nyu-shopcart-service-f20-pipeline") deployed [shopcarts](https://github.com/NYU-DevOps2020-shopcarts/shopcarts/releases/tag/deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028 "deploy-ibm-yp-us-south-kfh226-nyu.edu-prod-20201208-144028") to [prod](https://console.bluemix.net/apps/ac06a6b3-040d-43d7-b290-6bfbba3f8c41?env_id=ibm:yp:us-south "ibm:yp:us-south:kfh226@nyu.edu:prod"), including commit a1564bf02f0c1f066ceea9d42a70dcf118400443