adding logging to services and update read me
NYU-DevOps2020-shopcarts/shopcarts pull request #29
Opened 2020-10-12 21:49 UTC by jules203

# Pull Request Template

## Checklist:

- [ ] I have written test cases for this change, and my code passed the test - **needed for this?**
- [x] I have updated documentation to reflect this change
- [x] I have attached this PR to an issue/user story
 I canceled the old PR for logging and made this new one

2020-10-12 22:53 UTC, KHafner commented
Should config.py be included as part of this PR? If that is included the checks should pass, correct?

2020-10-13 00:05 UTC, jules203 commented
@KHafner Added the config.py file!

2020-10-13 13:28 UTC, iLtc commented
Please run `git pull` and `git merge master` to merge all the latest changes to your branch. This should allow all the tests to pass.

2020-10-13 21:30 UTC, iLtc requested changes

2020-10-13 21:30 UTC, iLtc commented on service/models.py
> + @classmethod
Please fix this indent issue.

2020-10-14 01:17 UTC, iLtc approved these changes
LGTM, thanks!

2020-10-14 14:36 UTC, KHafner approved these changes

2020-10-14 19:33 UTC, merged